### PR TITLE
fix: add backgroundcolor to the line proxy type

### PR DESCRIPTION
**Pull request by chenjiahe01**
Problem: the line "proxy type" of the page "system proxy" doesn't have grey backgroundcolor like other lines.
Solution: I used addBackground() to make this line the same like others
Issue: #141 
Log:  add grey backgroundcolor to the line proxy type of page system proxy.

### CODE REVIEW

**Comment by chenjiahe01** [comment]
I don't know why commitlint check failed. It keeps telling me that my body is empty...

**Comment by Decodetalkers** [comment]
add
```
Log: 
```
 to the last line of your commit

**Comment by chenjiahe01** [comment]
> add
> 
> ```
> Log: 
> ```
> 
> to the last line of your commit
> 
> and you need to asign the cla

Thanks, commitlint check has done. 
And I will sign the CLA soon.

**Comment by chenjiahe01** [comment]
> 

Hello, I have already signed the CLA.

**Comment by chenjiahe01** [comment]
> add
> 
> ```
> Log: 
> ```
> 
> to the last line of your commit
> 
> and you need to asign the cla

Hello, I've already signed the CLA.

**Comment by Decodetalkers** [comment]
no.. you should not merge the master, you need to rebase

```
git pull origin master --rebase
```

on your branch

and force push again

**Comment by chenjiahe01** [comment]
> ```
> git reset HEAD~1
> git checkout .
> git pull origin master --rebase
> ```
> 
> you should reset the second commit and force push
> 
> you should update branch with rebase

done

**Review by 18202781743 — APPROVED** [review]

**Pull request merged**
