### PR TITLE
Update license information on READMEs

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by bkmgit** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by bkmgit** [comment]
recheck

**Comment by BLumia** [comment]
Thanks for the patch! I'm not sure if this is the correct fix tho. It seems most of the source files declared them as GPL instead if LGPL, maybe the LICENSE file in the root folder is the one that needs to be updated instead.

We'll check which is the actual case and let you know when we got an answer.

**Comment by 18202781743** [comment]
> We'll check which is the actual case and let you know when we got an answer.

这个有结论了么？

**Comment by BLumia** [comment]
> 这个有结论了么？

事太杂跟进漏了 = =

我下周一问下法务那边，如果周一我还没更新这个进度的话可以再 ping 我一下 😂

**Comment by Decodetalkers** [comment]
@BLumia  这个pr那么这样就可以合并了吗

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/dde-network-core/pull/216 should addressed this issue :)

**Comment by Decodetalkers** [comment]
@BLumia 我是希望我把代码的处理了，然后可以合并这个的。。emm

**Comment by BLumia** [comment]
oh sorry

**Review by Decodetalkers — APPROVED** [review]

**Comment by Decodetalkers** [comment]
Thanks very much

**Pull request merged**
